### ISSUE TITLE
Simplify the library

### ISSUE THREAD

**Issue by wemeetagain** [achingbrain/uint8-varint#27]
In practice, this library is used for length-prefixing data, and decoding length-prefixed data.
I'd like to see this library simplified/minimized with that in mind:
- removing extraneous functionality
- removing dependencies
- optimizing for the cases that are used in practice
- exposing underlying functionality

I would suggest the following:
- move unsigned and zigzag variants to another library
- remove longbits and accessor-bits dependencies
- optimize decode and encode
- expose Uint8Array-only and Uint8ArrayList-only variants

I think that this direction will allow this library to more easily be incorporated across the libp2p etc ecosystem and areas where higher performance and simplicity are desired.

I'll open a PR with these suggestions to show what I'm talking about.

**Comment by achingbrain** [comment]
Fixed by #30
